// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm0vgqnkWuyS8Axv1guDxIPxkz7CFPLW4',
    appId: '1:77339663259:android:cf83c7bcd13cb6cb08df3e',
    messagingSenderId: '77339663259',
    projectId: 'routineplanner-2963c',
    storageBucket: 'routineplanner-2963c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPe1053vjF8j9AoGRxx8C9PFVwEdM4RA',
    appId: '1:77339663259:ios:bcdd7a9be3dc893d08df3e',
    messagingSenderId: '77339663259',
    projectId: 'routineplanner-2963c',
    storageBucket: 'routineplanner-2963c.firebasestorage.app',
    iosBundleId: 'com.example.routinePlanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYb3vMQHL_9eHrG4m9RatVBNUg88tp14U',
    appId: '1:77339663259:web:2fd420d659966d8b08df3e',
    messagingSenderId: '77339663259',
    projectId: 'routineplanner-2963c',
    authDomain: 'routineplanner-2963c.firebaseapp.com',
    storageBucket: 'routineplanner-2963c.firebasestorage.app',
    measurementId: 'G-VJZ1TDKJLF',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYb3vMQHL_9eHrG4m9RatVBNUg88tp14U',
    appId: '1:77339663259:web:43c804c7926bf80a08df3e',
    messagingSenderId: '77339663259',
    projectId: 'routineplanner-2963c',
    authDomain: 'routineplanner-2963c.firebaseapp.com',
    storageBucket: 'routineplanner-2963c.firebasestorage.app',
    measurementId: 'G-R5G2D57N4Z',
  );

}